### ISSUE TITLE
带 顶置 文章日期较老  漏文章

### ISSUE THREAD

**Issue by marklove5102** [cocowool/py-cnblogs#3]
采集出来的 html 数量少于 博客  显示 文章 :: x

我见过整个页面都是顶置的博客

当然目前我直接传最新的链接进去的。可以临时解决问题

**Comment by cocowool** [comment]
能否提供个地址，我测试下。置顶这部分逻辑确实没特殊处理过。

**Comment by marklove5102** [comment]
https://www.cnblogs.com/zyl910
顶置的帖子是 2012-04-26
最新  
随笔档案 (195)
2020年8月(1)
我修改后的 可以下载193个。 少两个。。 东西太多懒得确认啥问题了。
